### ISSUE TITLE
Firefox missing other languages after update to 22.04

### ISSUE THREAD

**Issue by letatcest** [pop-os/packaging-firefox#5]
Since the update from 21.10 to 22.04 I cannot use any other language as a spell checker in Firefox than US English. I can't seem to find out why. 
- other languages work in Thunderbird
- other languages are installed (Hunspell dictionaries)
- other languages are active via global OS Settings
- when I try to install other languages via Firefox settings, all are installed already
- when I try to install dictionaries via add-ons, they are installed already (for ex. https://addons.mozilla.org/en-US/firefox/addon/nederlands-nl-language-pack/ )
All this makes sense, as the OS is upgraded and everything was installed.
See screenshots for reference (I removed many of the languages in the meantime, I don't need any other French than French ;) )
![Screenshot from 2022-05-03 13-54-42](https://user-images.githubusercontent.com/12709182/166469042-c55f029a-7eef-4f61-8ecd-6d8bb933bbc1.png)
![Screenshot from 2022-05-03 13-58-26](https://user-images.githubusercontent.com/12709182/166469050-9406877b-672c-4b26-9da0-f338dc4df047.png)
![Screenshot from 2022-05-03 16-04-21](https://user-images.githubusercontent.com/12709182/166469054-4c9256ed-1a17-4e41-87f5-2d3832a26924.png)

**Comment by letatcest** [comment]
I was hoping the upgrade to Firefox 100 would do the trick, but no. The .deb variant doesn't do it. I installed the flatpak using the software centre and now it works as advertised (very unfortunate to have to re-login to everything, I fortunately have a firefox account)

One thing which bugs me: why is it totally unclear what you install (deb, flatpak?), which version and what size in the Pop!_Shop?

But I close the issue, unless one wants a fix for the deb-version, then one can reopen.

**Comment by rimas-kudelis** [comment]
I had this problem as well. A simple workaround is to go to `about:config` and add a new parameter there:
Name: `spellchecker.dictionary_path`
Type: string
Value: `/usr/share/hunspell`

@letatcest, may I suggest you reopen this issue, so that System76 could fix it on their side too?
